# docker-compose.yml
version: "3"

services:
  node:
    image: "node:12.15.0"
    ports:
      - "80:80"
      - "443:443"
    environment:
      NODE_ENV: "development"
    working_dir: /home/node/app/
    volumes:
      - .:/home/node/app/:ro
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run start-watch"
